config/routes.rb
MyNotes::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users
  root :to => "Notes#index"

  resources :notes do
    member do
      get "preview"
    end
    collection do
      get "search"
    end
  end

end

app/models/note.rb
class Note < ActiveRecord::Base

	self.per_page = 3
	validates_presence_of :title, :user_id, :content

	#☺liaison entre notes et users. 1 user à plusieur notes
	belongs_to :user

	def self.searchInTitle(string)
		where('lower(title) like ? or lower(content) like ?', "%#{string.downcase}%", "%#{string.downcase}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	validates_presence_of :name
	validates_format_of :name, :with => /\A[a-zA-Z]+\z/, :message => "Uniquement des lettres"

	#☺liaison entre notes et users. 1 user à plusieur notes
	has_many :notes

	def to_s
		self.name
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  def authenticate_admin_user!
    redirect_to(new_user_session_path) and return if user_signed_in? && !current_user.admin?
    authenticate_user!
  end

  def current_admin_user
    return nil if user_signed_in? && !current_user.admin?
    current_user
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    #@notes = Note.all
    @notes = Note.paginate :page => params[:page]
    request.xhr? ? render(@notes, :layout => false) : render(:index)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/search
  # GET /notes/search.json
  def search
    @notes = Note.searchInTitle(params[:keywords]).paginate :page => params[:page]
    @keywords_value = params[:keywords]
    render "index"
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNotes</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a href="/" class="brand">Programme de notes</a>
      <div class = "btn-group pull-right">
        <ul class = "nav">
          <% if user_signed_in? %>
              <li><%= link_to 'Administration', admin_dashboard_path%></li>
              <li><%= link_to current_user, edit_user_registration_path%></li>
              <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete%></li>
          <%else%>
              <li><%= link_to 'Register', new_user_registration_path%></li>
              <li><%= link_to 'Login', new_user_session_path%></li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <%if flash[:notice].present?%>
      <div class = "alert alert-success">
        <%= flash[:notice]%>
      </div>
  <%end%>
  <%if flash[:alert].present?%>
      <div class = "alert alert-error">
        <%= flash[:alert]%>
      </div>
  <%end%>
    <%= yield %>
</div>
</body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for(@note) do |f| %>
    <%= f.input :title,:label => 'Titre' %>
    <%= f.input :user,:label => 'Utilisateur' %>
    <%= f.input :content,:label => 'Contenu',:placeholder =>'Veuillez encoder votre texte ici' %>
    <script type="text/javascript">
        $('#note_content').wysihtml5();
    </script>
    <%= f.button :submit, 'Envoyer', :class => "btn btn-primary" %>
<% end %>

app/views/notes/_note.html.erb
<tr>
  <td><%= note.title %></td>
  <td><%= note.user %></td>
  <td><%= note.content.html_safe %></td>
  <td width='10'>
    <%= link_to note, :class => "btn" do %>
      <i class="icon-search"></i>
    <%end%>
  </td>
  <td width='10'>
    <%= link_to edit_note_path(note), :class => "btn" do %>
      <i class="icon-edit"></i>
      <%end%>
  </td>
  <td width='10'>
    <%= link_to note, confirm: 'Etes vous sûr de vouloir supprimer cette note ?', method: :delete, :class => "btn" do %>
      <i class="icon-trash"></i>
      <%end%>
  </td>
</tr>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note, :class => "btn btn-primary"  %> 
<%= link_to 'Back', notes_path, :class => "btn btn-primary"  %>

app/views/notes/index.html.erb
<h1>Liste de notes</h1>
<%= form_tag(search_notes_path, :method => "get") do %>
  <%= label_tag(:keywords, "Recherche:") %>
<div class="input-append">
  <%= text_field_tag(:keywords,@keywords_value) %>
  <%= submit_tag("Envoyer",:class => "btn btn-primary") %>
</div>
<br /><br />
<% end %>

<table id='notes' class="table table-striped table-condensed">
  <tbody>
    <tr>
      <th>Titre</th>
      <th>Utilisateur</th>
      <th>Contenu</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  <%= render @notes %>
  </tbody>
</table>

<%= link_to "more", "javascript:", {:id => "more_notes", :class => "btn btn-primary"} %>
<%#= will_paginate @notes %>

<br />

<%= link_to 'New Note', new_note_path, :class => "btn btn-primary" %>  <%= link_to 'Home', notes_path, :class => "btn btn-primary" %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path, :class => "btn btn-primary"  %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>User:</b>
  <%= @note.user %>
</p>

<p>
  <b>Content:</b>
  <%= @note.content.html_safe %>
</p>


<%= link_to 'Edit', edit_note_path(@note), :class => "btn btn-primary"  %> 
<%= link_to 'Back', notes_path, :class => "btn btn-primary"  %>